# Generated by Django 3.2.15 on 2022-10-21 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_producto_cantidad_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_subcategoria', models.CharField(max_length=50, verbose_name='Nombre de Categoría')),
                ('create_at', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('modify_at', models.DateField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.categoria')),
            ],
            options={
                'verbose_name_plural': 'Subcategoria',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.subcategoria'),
        ),
    ]
