# Generated by Django 3.2.15 on 2022-11-10 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_forma', models.CharField(max_length=20, verbose_name='Forma de Pago')),
            ],
            options={
                'verbose_name_plural': 'Formas de Pago',
            },
        ),
        migrations.CreateModel(
            name='DetallePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=30, verbose_name='Banco')),
                ('titular', models.CharField(max_length=250, verbose_name='Titular de la cuenta')),
                ('cc_titular', models.CharField(max_length=20, verbose_name='Documento de identidad')),
                ('total_pago', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Total a Pagar')),
                ('iva_pago', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Total a Pagar')),
                ('create_at', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('modify_at', models.DateField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('forma_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.formapago')),
            ],
            options={
                'verbose_name_plural': 'Detalle de Pago',
            },
        ),
    ]
