# Generated by Django 3.2.15 on 2022-10-11 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import registration.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=registration.models.subir_avatar)),
                ('genero_user', models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino'), ('Otro', 'Otro')], default='Otro', max_length=20, verbose_name='Género')),
                ('tipo_identificacion', models.CharField(choices=[('Registro civil', 'Registro civil'), ('Tarjeta de Identidad', 'Tarjeta de Identidad'), ('Cédula de Ciudadanía', 'Cédula de Ciudadanía'), ('Cédula de Extrangería', 'Cédula de Extrangería'), ('Pasaporte', 'Pasaporte'), ('Permiso Especial de Circulación', 'Permiso Especial de Circulación'), ('Sin Identificar', 'Sin Identificar')], default='Sin Identificar', max_length=50, verbose_name='Tipo de Documento de Identidad')),
                ('identificacion_usuario', models.CharField(max_length=50, verbose_name='Número de Identificación')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección Postal')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('create_at', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('modify_at', models.DateField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
                'ordering': ['usuario__username'],
            },
        ),
    ]
