# Generated by Django 3.2.15 on 2022-10-14 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'ordering': ['usuario__username'], 'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuarios'},
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='complemento_dirección',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento de dirección'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Completos'),
        ),
    ]
